[package]
name = "agnostic"
version = "0.0.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Agnostic is a trait for users who want to write async runtime-agnostic crate."

[features]
default = []
tokio = ["dep:tokio", "tokio-stream"]
async-std = ["dep:async-std", "async-io", "pin-project-lite"]
smol = ["dep:smol", "pin-project-lite", "async-io"]
monoio = ["dep:monoio", "async-channel"]

[dependencies]
async-trait = "0.1"
futures-util = { version = "0.3" }

tokio = { version = "1.28", default-features = false, features = ["rt", "time", "sync", "macros"], optional = true }
tokio-stream = { version = "0.1", default-features = false, optional = true, features = ["time"] }

async-std = { version = "1.12", optional = true, features = ["unstable"] }
async-io = { version = "1.12", optional = true }
pin-project-lite = { version = "0.2", optional = true }
smol = { version = "1.3", default-features = false, optional = true }

monoio = { version = "0.1", optional = true, features = ["sync"] }
async-channel = { version = "1.8", optional = true }