[workspace]
members = ["agnostic", "lite"]
resolver = "2"

[workspace.dependencies]
futures-util = { version = "=0.3.29", default-features = false }
pin-project-lite = "0.2"

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT/Apache-2.0"
rust-version = "1.75.0"
repository = "https://github.com/al8n/agnostic"
homepage = "https://github.com/al8n/agnostic"
keywords = ["async", "runtime", "agnostic", "trait"]

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]