[package]
name = "agnostic-dns"
version = "0.2.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["asynchronous", "network-programming"]
keywords = ["agnostic", "dns"]
description = "`agnostic-dns` is an async runtime agnostic layer over `hickory-dns`."

[features]
default = []

tokio = ["agnostic-net/tokio"]
async-std = ["agnostic-net/async-std"]
smol = ["agnostic-net/smol"]

tracing = ["dep:tracing"]

dns-over-quic = [
  "hickory-resolver/dns-over-quic",
  "hickory-proto/dns-over-quic",
  "dns-over-rustls",
]
dns-over-h3 = [
  "hickory-resolver/dns-over-h3",
  "dns-over-rustls",
  "hickory-proto/dns-over-h3",
]
dns-over-https-rustls = [
  "hickory-resolver/dns-over-https-rustls",
  "hickory-proto/dns-over-https-rustls",
  "dns-over-rustls",
]
dns-over-rustls = [
  "hickory-resolver/dns-over-rustls",
  "hickory-proto/dns-over-rustls",
]
dns-over-openssl = [
  "hickory-resolver/dns-over-openssl",
  "hickory-proto/dns-over-openssl",
]
dns-over-native-tls = [
  "hickory-resolver/dns-over-native-tls",
  "hickory-proto/dns-over-native-tls",
]
dns-webpki-roots = [
  "hickory-proto/webpki-roots",
  "hickory-resolver/webpki-roots",
]
dns-native-certs = [
  "hickory-proto/native-certs",
  "hickory-resolver/native-certs",
]
dnssec-openssl = [
  "hickory-proto/dnssec-openssl",
  "hickory-resolver/dnssec-openssl",
]
dnssec-ring = [
  "dnssec",
  "hickory-proto/dnssec-ring",
  "hickory-resolver/dnssec-ring",
]
dnssec = [ "hickory-proto/dnssec", "hickory-resolver/dnssec"]

[target.'cfg(target_family = "wasm")'.dependencies]
hickory-resolver = { version = "0.24", default-features = false, optional = true }

[target.'cfg(unix)'.dependencies]
hickory-resolver = { version = "0.24", default-features = false, features = [
  "system-config",
] }

[target.'cfg(windows)'.dependencies]
hickory-resolver = { version = "0.24", default-features = false, features = [
  "system-config",
] }

[dependencies]
async-trait = "0.1"
agnostic-net.workspace = true
futures-util.workspace = true
hickory-proto = { version = "0.24", default-features = false }
resolv-conf = { version = "0.7", default-features = false }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt"] }
