[package]
name = "agnostic"
version = "0.1.21"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Agnostic is a helpful crate for users who want to write async runtime-agnostic crate."
repository = "https://github.com/al8n/agnostic"
documentation = "https://docs.rs/agnostic"
readme = "README.md"
keywords = ["async", "runtime", "agnostic", "trait"]
categories = ["asynchronous"]
homepage = "https://github.com/al8n/agnostic"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

# # ebable zero cost async/await, only works on rust nightly compiler
# nightly = []

dns = ["net", "trust-dns-resolver", "resolv-conf", "trust-dns-proto", "thiserror"]

net = ["atomic", "io", "socket2", "tokio?/net", "tokio?/io-util", "tokio?/io-std", "async-std?/default"]
io = ["futures-util/io"]

# This feature must be used with net feature
# by enable this feature, TcpStream will implement
# both futures::AsyncRead/AsyncWrite and tokio::io::AsyncRead/AsyncWrite.
# But if you are using tokio, this feature can be ignored.
tokio-compat = ["tokio-util/compat", "dep:tokio"]

tokio = ["dep:tokio", "pin-project-lite", "tokio-stream", "tokio/rt", "tokio/sync", "tokio/macros", "tokio/time", "tokio-compat"]
async-std = ["dep:async-std", "async-io", "pin-project-lite"]
smol = ["dep:smol", "pin-project-lite", "async-io"]

tracing = ["dep:tracing"]

# Note: this crate does not support net features for monoio
# monoio = ["dep:monoio", "async-channel", "monoio-compat"]

[target.'cfg(unix)'.dependencies]
socket2 = { version = "0.5", optional = true }
trust-dns-resolver = { version = "0.23", default-features = false, optional = true, features = ["system-config"] }

[target.'cfg(windows)'.dependencies]
socket2 = { version = "0.5", optional = true }
trust-dns-resolver = { version = "0.23", default-features = false, optional = true, features = ["system-config"] }

[target.'cfg(target_family = "wasm")'.dependencies]
trust-dns-resolver = { version = "0.23", default-features = false, optional = true }

[dependencies]
atomic = { version = "0.5", optional = true }
async-trait = "0.1"
futures-util = { version = "0.3" }

tokio = { version = "1.32", default-features = false, optional = true }
tokio-stream = { version = "0.1", default-features = false, optional = true, features = ["time"] }
tokio-util = { version = "0.7", default-features = false, optional = true, features = ["compat"] }

async-std = { version = "1.12", optional = true, features = ["unstable"] }
async-io = { version = "1.12", optional = true }
pin-project-lite = { version = "0.2", optional = true }
smol = { version = "1.3", default-features = false, optional = true }

# monoio = { version = "0.1", optional = true, features = ["sync"] }
# monoio-compat = { version = "0.1", optional = true }
async-channel = { version = "1.8", optional = true }

trust-dns-proto = { version = "0.23", default-features = false, optional = true }
resolv-conf = { version = "0.7", default-features = false, optional = true }
thiserror = { version = "1", optional = true }

tracing = { version = "0.1", optional = true }

[dev-dependencies]
tokio = { version = "1.32", features = ["full"] }