[package]
name = "agnostic"
version = "0.2.23"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Agnostic is a helpful crate for users who want to write async runtime-agnostic crate."
repository = "https://github.com/al8n/agnostic"
documentation = "https://docs.rs/agnostic"
readme = "README.md"
keywords = ["async", "runtime", "agnostic", "trait"]
categories = ["asynchronous"]
homepage = "https://github.com/al8n/agnostic"
rust-version = "1.75.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

dns = ["net", "hickory-resolver", "resolv-conf", "hickory-proto", "thiserror"]
dns-over-quic = ["dns", "hickory-resolver/dns-over-quic", "hickory-proto/dns-over-quic", "dns-over-rustls"]
dns-over-h3 = ["dns", "hickory-resolver/dns-over-h3", "dns-over-rustls", "hickory-proto/dns-over-h3"]
dns-over-https-rustls = ["dns", "hickory-resolver/dns-over-https-rustls", "hickory-proto/dns-over-https-rustls", "dns-over-rustls"]
dns-over-rustls = ["dns", "hickory-resolver/dns-over-rustls", "hickory-proto/dns-over-rustls"]
dns-over-openssl = ["dns", "hickory-resolver/dns-over-openssl", "hickory-proto/dns-over-openssl"]
dns-over-native-tls = ["dns", "hickory-resolver/dns-over-native-tls", "hickory-proto/dns-over-native-tls"]
dns-webpki-roots = ["dns", "hickory-proto/webpki-roots", "hickory-resolver/webpki-roots"]
dns-native-certs = ["dns", "hickory-proto/native-certs", "hickory-resolver/native-certs"]
dnssec-openssl = ["dns", "hickory-proto/dnssec-openssl", "hickory-resolver/dnssec-openssl"]
dnssec-ring = ["dnssec", "hickory-proto/dnssec-ring", "hickory-resolver/dnssec-ring"]
dnssec = ["dns", "hickory-proto/dnssec", "hickory-resolver/dnssec"]

quinn = ["quinn/native-certs", "quinn/tls-rustls", "quinn/log", "quinn-udp", "net"]

net = ["atomic-time/std", "io", "socket2", "tokio?/net", "tokio?/io-util", "tokio?/io-std", "async-std?/default"]
io = ["futures-util/io"]

# This feature must be used with net feature
# by enable this feature, TcpStream will implement
# both futures::AsyncRead/AsyncWrite and tokio::io::AsyncRead/AsyncWrite.
# But if you are using tokio, this feature can be ignored.
tokio-compat = ["tokio-util/compat", "dep:tokio"]

tokio = ["dep:tokio", "quinn?/runtime-tokio", "pin-project-lite", "tokio-stream", "tokio/rt", "tokio/sync", "tokio/macros", "tokio/time", "tokio-compat", "futures-timer", "wg/tokio"]
async-std = ["dep:async-std", "quinn?/runtime-async-std", "async-io", "pin-project-lite", "wg/future"]
smol = ["dep:smol", "pin-project-lite", "async-io", "wg/future"]

tracing = ["dep:tracing"]

[target.'cfg(unix)'.dependencies]
socket2 = { version = "0.5", optional = true }
hickory-resolver = { version = "0.24", default-features = false, optional = true, features = ["system-config"] }

[target.'cfg(windows)'.dependencies]
socket2 = { version = "0.5", optional = true }
hickory-resolver = { version = "0.24", default-features = false, optional = true, features = ["system-config"] }

[target.'cfg(target_family = "wasm")'.dependencies]
hickory-resolver = { version = "0.24", default-features = false, optional = true }

[dependencies]
atomic-time = { version = "0.1", optional = true, default-features = false }
async-trait = "0.1"
futures-util = { version = "0.3" }
wg = { version = "0.7", features = ["triomphe"] }

tokio = { version = "1", default-features = false, optional = true }
tokio-stream = { version = "0.1", default-features = false, optional = true, features = ["time"] }
tokio-util = { version = "0.7", default-features = false, optional = true, features = ["compat"] }
futures-timer = { version = "3", optional = true }


async-std = { version = "1.12", optional = true, features = ["unstable"] }
async-io = { version = "2.1", optional = true }
pin-project-lite = { version = "0.2", optional = true }
smol = { version = "2", default-features = false, optional = true }

async-channel = { version = "2", optional = true }

hickory-proto = { version = "0.24", default-features = false, optional = true }
resolv-conf = { version = "0.7", default-features = false, optional = true }
thiserror = { version = "1", optional = true }

quinn = { version = "0.10", optional = true, default-features = false }
quinn-udp = { version = "0.4", optional = true, default-features = false }

tracing = { version = "0.1", optional = true }

[dev-dependencies]
tokio = { version = "1.32", features = ["full"] }