[package]
name = "agnostic"
version = "0.6.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
description = "Agnostic is a helpful crate for users who want to write async runtime-agnostic crate."
documentation = "https://docs.rs/agnostic"
readme = "README.md"
categories = ["asynchronous"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

process = ["dep:agnostic-process"]
net = ["dep:agnostic-net"]
quinn = ["quinn/log", "quinn-udp"]

tokio-io = ["agnostic-io/tokio"]

## Runtime related features
tokio = [
  "agnostic-lite/tokio",
  "agnostic-net?/tokio",
  "agnostic-process?/tokio",
  "quinn?/runtime-tokio",
]
async-std = [
  "agnostic-lite/async-std",
  "agnostic-net?/async-std",
  "agnostic-process?/async-std",
  "quinn?/runtime-async-std",
]
smol = [
  "agnostic-lite/smol",
  "agnostic-process?/smol",
  "agnostic-net?/smol",
  "quinn?/runtime-smol",
]

tracing = ["dep:tracing"]

## DNS related features
dns = ["net", "agnostic-net/dns"]
dns-over-quic = [
  "dns",
  "agnostic-net/dns-over-quic",
]
dns-over-h3 = [
  "dns",
  "agnostic-net/dns-over-h3",
]
dns-over-https-rustls = [
  "dns",
  "agnostic-net/dns-over-https-rustls",
]
dns-over-rustls = [
  "dns",
  "agnostic-net/dns-over-rustls",
]
dns-over-openssl = [
  "dns",
  "agnostic-net/dns-over-openssl",
]
dns-over-native-tls = [
  "dns",
  "agnostic-net/dns-over-native-tls",
]
dns-webpki-roots = [
  "dns",
  "agnostic-net/dns-webpki-roots",
]
dns-native-certs = [
  "dns",
  "agnostic-net/dns-native-certs",
]
dnssec-openssl = [
  "dns",
  "agnostic-net/dnssec-openssl",
]
dnssec-ring = [
  "dnssec",
  "agnostic-net/dnssec-ring",
]
dnssec = ["dns", "agnostic-net/dnssec"]

[dependencies]
agnostic-lite = { workspace = true, features = ["time"] }
agnostic-net = { workspace = true, optional = true }
agnostic-process = { workspace = true, optional = true }
agnostic-io.workspace = true

quinn = { version = "0.11", optional = true, default-features = false }
quinn-udp = { version = "0.5", optional = true, default-features = false }

tracing = { version = "0.1", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
